### ISSUE TITLE
converted .schem file crashed my server

### ISSUE THREAD

**Issue by EmperorTomo** [GoldenDelicios/Lite2Edit#3]
Hi there, found this via Reddit, tried it on my server, alas it crashed. I converted a .litematic file into a .schem file as per the directions, and tried pasting this converted .schem file with WorldEdit on my private creative server. 

Here is the crash log,
https://mcpaste.io/0d02c4f2179c2a80

Thanks!

**Comment by EmperorTomo** [comment]
Thought it might have been a memory issue with my server, tried again and it seems that WorldEdit doesn't seem to like the usage of 'minecraft:' in it. https://mcpaste.io/4231e609163bad9b

**Comment by GoldenDelicios** [comment]
Hey there, could you provide the .litematic and .schem files so I can investigate further?

**Comment by EmperorTomo** [comment]
Whoops.

Im unable to provide the schem but you can replicate it by running the litematic through version 1.1.

Sorry for the delay.

**Comment by EmperorTomo** [comment]
https://drive.google.com/file/d/1xwgNNGucNoE0AFFwKM7NU4MiuqU0hYym/view?usp=drivesdk

**Comment by GoldenDelicios** [comment]
Hello, sorry for the delayed response. I've finally had some time to look into this issue.

> Unsupported key: minecraft:

It seems the tile entities in the original litematic lack IDs (e.g. minecraft:sign), which Lite2Edit cannot handle. Effectively, any tile entities will lose their data because of this, but the schematic is otherwise unaffected. This error doesn't cause the server crash.

> Detected stop event: java.lang.OutOfMemoryError: Java heap space

I did not run into this error on my server. Your server most likely does not have enough memory for WorldEdit to paste a schematic of this size. You can try to disable block/lighting updates by running `//perf` and disabling those effects, which should reduce memory usage. If your host allows, increasing allocated memory to the server might also help.

**Comment by ghost** [comment]
Hello how do you have the "import se...."?

**Comment by EmperorTomo** [comment]
> Hello how do you have the "import se...."?

What?
